:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-constraint-solving-ai-optaplanner

This guide walks you through the process of creating a https://github.com/spring-projects/spring-boot[Spring Boot]
application with https://www.optaplanner.org/[OptaPlanner]'s constraint solving Artificial Intelligence.
This application optimizes a school timetable for students and teachers.

== What you'll build

Your application will assign `Lesson` instances to `Timeslot` and `Room` instances.
It'll generate an optimal high school timetable that adheres to hard and soft scheduling constraints.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== Create the build file

// TODO


== Create the domain objects

// TODO

`src/main/java/com/example/domain/Timeslot.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/domain/Timeslot.java[]
----

`src/main/java/com/example/domain/Room.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/domain/Room.java[]
----

`src/main/java/com/example/domain/Lesson.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/domain/Lesson.java[]
----


== Create the planning solution

// TODO

`src/main/java/com/example/domain/TimeTable.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/domain/TimeTable.java[]
----


== Define the hard and soft constraints

// TODO

`src/main/java/com/example/solver/TimeTableConstraintProvider.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/solver/TimeTableConstraintProvider.java[]
----


== Create the solver service

// TODO

`src/main/java/com/example/solver/TimeTableService.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/solver/TimeTableService.java[]
----



== Make the application executable

Package everything in a single, executable JAR file, driven by a good old Java `main()` method:

`src/main/java/com/example/TimeTableSpringBootApp.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/TimeTableSpringBootApp.java[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


// TODO



== Test the application

// TODO
Now that the application is running, you can test it.



== Summary

// TODO
Congratulations! You've just developed a https://spring.io/[Spring] application with https://www.optaplanner.org/[OptaPlanner]!




== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]
* https://spring.io/guides/gs/accessing-data-rest/[Accessing JPA Data with REST]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
