:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-constraint-solving-ai-optaplanner

This guide walks you through the process of creating a https://github.com/spring-projects/spring-boot[Spring Boot]
and https://www.optaplanner.org/[OptaPlanner] application
that optimizes a school timetable for students and teachers.

== What you'll build

You'll assign `Lesson` POJOs (Plain Old Java Objects) to `Timeslot` and `Room` POJOs
to generate an optimal high school timetable which adheres to hard and soft scheduling constraints
by using OptaPlanner's constraint solving Artificial Intelligence on Spring Boot.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== Create a resource controller

Create a new controller for your Spring application:

`src/main/java/hello/GreetingController.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/hello/GreetingController.java[]
----

NOTE: The above example does not specify `GET` vs. `PUT`, `POST`, and so forth, because `@RequestMapping` maps all HTTP operations by default. Use `@RequestMapping(method=GET)` to narrow this mapping.


== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated below creates a standalone application. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/java/hello/Application.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/hello/Application.java[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


Logging output is displayed. The service should be up and running within a few seconds.


== Test the application

Now that the application is running, you can test it.


== Summary

Congratulations! You've just developed a Spring application!




include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
